// import { UsersEntity } from 'src/users/entities/users.entity';
// import { EMembershipStatus, EStudentStatus } from 'src/users/enums';

// export const mockUsers: UsersEntity[] = [
//   {
//     userId: 1,
//     username: '고길동',
//     nickname: '소드마스터',
//     phoneNumber: '010-1111-2222',
//     email: 'gildong@example.com',
//     password: '!Hashedpassword',
//     isTempPassword: null,
//     membershipStatus: EMembershipStatus.APPROVED_MEMBER, // 3(정회원)
//     studentStatus: EStudentStatus.GRADUATE, // 졸업생
//     isAdmin: false,
//     certificationDocumentUrl: 'http://example.com/certification1',
//     rejected: false,
//     createdAt: new Date('2023-01-01T00:00:00Z'),
//     suspensionEndDate: null,
//     deletedAt: null,
//     posts: [],
//     comments: [],
//     replies: [],
//     scraps: [],
//     logins: [],
//     submittedPostReports: [],
//     receivedPostReports: [],
//     submittedCommentReports: [],
//     receivedCommentReports: [],
//   },
//   {
//     userId: 2,
//     username: '도우너',
//     nickname: '루돌프사람코',
//     phoneNumber: '987-654-3210',
//     email: 'downer@example.com',
//     password: 'Hashedpassword!',
//     isTempPassword: null,
//     membershipStatus: EMembershipStatus.EMAIL_VERIFIED,
//     studentStatus: EStudentStatus.CURRENT,
//     isAdmin: false,
//     certificationDocumentUrl: 'http://example.com/certification2',
//     rejected: false,
//     createdAt: new Date('2023-02-01T00:00:00Z'),
//     suspensionEndDate: new Date('2023-03-01T00:00:00Z'),
//     deletedAt: null,
//     posts: [],
//     comments: [],
//     replies: [],
//     scraps: [],
//     logins: [],
//     submittedPostReports: [],
//     receivedPostReports: [],
//     submittedCommentReports: [],
//     receivedCommentReports: [],
//   },
//   {
//     userId: 3,
//     username: '민주원',
//     nickname: 'zooone1',
//     phoneNumber: '321-654-9870',
//     email: 'zooone1@example.com',
//     password: '!hashedpassword',
//     isTempPassword: null,
//     membershipStatus: EMembershipStatus.NON_MEMBER,
//     studentStatus: EStudentStatus.GRADUATE,
//     isAdmin: false,
//     certificationDocumentUrl: 'http://example.com/certification3',
//     rejected: false,
//     createdAt: new Date('2023-03-01T00:00:00Z'),
//     suspensionEndDate: null,
//     deletedAt: null,
//     posts: [],
//     comments: [],
//     replies: [],
//     scraps: [],
//     logins: [],
//     submittedPostReports: [],
//     receivedPostReports: [],
//     submittedCommentReports: [],
//     receivedCommentReports: [],
//   },
//   {
//     userId: 4,
//     username: '유예성',
//     nickname: 'yesU!',
//     phoneNumber: '654-321-0987',
//     email: 'yesyesU@example.com',
//     password: 'hashedpassword!!',
//     isTempPassword: null,
//     membershipStatus: EMembershipStatus.APPROVED_MEMBER,
//     studentStatus: EStudentStatus.CURRENT,
//     isAdmin: false,
//     certificationDocumentUrl: 'http://example.com/certification4',
//     rejected: false,
//     createdAt: new Date('2023-04-01T00:00:00Z'),
//     suspensionEndDate: new Date('2023-05-01T00:00:00Z'),
//     deletedAt: null,
//     posts: [],
//     comments: [],
//     replies: [],
//     scraps: [],
//     logins: [],
//     submittedPostReports: [],
//     receivedPostReports: [],
//     submittedCommentReports: [],
//     receivedCommentReports: [],
//   },
//   {
//     userId: 5,
//     username: 'Charlie Brown',
//     nickname: 'charliebrown',
//     phoneNumber: '555-666-7777',
//     email: 'charlie@example.com',
//     password: 'hashedpassword',
//     isTempPassword: null,
//     membershipStatus: EMembershipStatus.APPROVED_MEMBER,
//     studentStatus: EStudentStatus.CURRENT,
//     isAdmin: false,
//     certificationDocumentUrl: 'http://example.com/certification5',
//     rejected: false,
//     createdAt: new Date('2023-05-01T00:00:00Z'),
//     suspensionEndDate: null,
//     deletedAt: null,
//     posts: [],
//     comments: [],
//     replies: [],
//     scraps: [],
//     logins: [],
//     submittedPostReports: [],
//     receivedPostReports: [],
//     submittedCommentReports: [],
//     receivedCommentReports: [],
//   },
//   {
//     userId: 6,
//     username: 'Diana Prince',
//     nickname: 'dianaprince',
//     phoneNumber: '888-999-0000',
//     email: 'diana@example.com',
//     password: 'hashedpassword',
//     isTempPassword: null,
//     membershipStatus: EMembershipStatus.APPROVED_MEMBER,
//     studentStatus: EStudentStatus.GRADUATE,
//     isAdmin: false,
//     certificationDocumentUrl: 'http://example.com/certification6',
//     rejected: false,
//     createdAt: new Date('2023-06-01T00:00:00Z'),
//     suspensionEndDate: null,
//     deletedAt: null,
//     posts: [],
//     comments: [],
//     replies: [],
//     scraps: [],
//     logins: [],
//     submittedPostReports: [],
//     receivedPostReports: [],
//     submittedCommentReports: [],
//     receivedCommentReports: [],
//   },
//   {
//     userId: 7,
//     username: 'Eve Adams',
//     nickname: 'eveadams',
//     phoneNumber: '222-333-4444',
//     email: 'eve@example.com',
//     password: 'hashedpassword',
//     isTempPassword: null,
//     membershipStatus: EMembershipStatus.APPROVED_MEMBER,
//     studentStatus: EStudentStatus.CURRENT,
//     isAdmin: false,
//     certificationDocumentUrl: 'http://example.com/certification7',
//     rejected: false,
//     createdAt: new Date('2023-07-01T00:00:00Z'),
//     suspensionEndDate: null,
//     deletedAt: null,
//     posts: [],
//     comments: [],
//     replies: [],
//     scraps: [],
//     logins: [],
//     submittedPostReports: [],
//     receivedPostReports: [],
//     submittedCommentReports: [],
//     receivedCommentReports: [],
//   },
//   {
//     userId: 8,
//     username: 'Frank Castle',
//     nickname: 'frankcastle',
//     phoneNumber: '333-444-5555',
//     email: 'frank@example.com',
//     password: 'hashedpassword',
//     isTempPassword: null,
//     membershipStatus: EMembershipStatus.APPROVED_MEMBER,
//     studentStatus: EStudentStatus.GRADUATE,
//     isAdmin: false,
//     certificationDocumentUrl: 'http://example.com/certification8',
//     rejected: false,
//     createdAt: new Date('2023-08-01T00:00:00Z'),
//     suspensionEndDate: null,
//     deletedAt: null,
//     posts: [],
//     comments: [],
//     replies: [],
//     scraps: [],
//     logins: [],
//     submittedPostReports: [],
//     receivedPostReports: [],
//     submittedCommentReports: [],
//     receivedCommentReports: [],
//   },
// ];
